image: python

before_script:
  - ls -la
  - pip install -r ./vm/salt/requirements.txt

# unittest stage
testing:
  script:
    - echo running tests...
    - pytest web-scraper/metrics/preprocessor.py \
      web-scraper/metrics/metrics.py \
      web-scraper/scraper.py \
      web_scraper/tests.
  stage: test

# stages list
stages:
  - test
