image: python

before_script:
  - ls -la
  - pip install -r ./vm/salt/requirements.txt

# unittest stage
testing:
  script:
    - echo running tests...
    - ./web-scraper/tests/run_tests.sh
  stage: test

# stages list
stages:
  - test
