image: python

before_script:
  - pip install -r /vm/salt/requirements.txt

# stage for build external libs
preparing:
  script:
    - echo preparing job...
  stage: build

# unittest stage
testing:
  script:
    - echo running tests...
    - echo running ...
    - /env/bin/pytest web-scraper/metrics/preprocessor.py
    - echo running GAME TESTS...
    - python3 testgame.py -id .
  stage: test

# stages list
stages:
  - build
  - test
