image: python

before_script:
  - ls -la
  - pip install -r ./vm/salt/requirements.txt

# unittest stage
testing:
  script:
    - echo running tests...
    - pytest web-scraper/metrics/preprocessor.py .
  stage: test

# stages list
stages:
  - build
  - test
